### ISSUE TITLE
Layout e Logotipos de Tela de Busca

### ISSUE THREAD

**Issue by barbier** [MinisterioPublicoRJ/sinapse#41]
A tela de busca precisa de refino para que possua logotipo Conexão, MP em Mapas e estilo com melhor acabamento.

**Comment by bakudas** [comment]
![layout-sinapse.png](https://images.zenhubusercontent.com/5b3cf068cfaf12775898a112/dd48cb61-93b1-40cf-b97d-89ba650467bb)
