### ISSUE TITLE
Alterar de dropdown para botões

### ISSUE THREAD

**Issue by victoralves** [MinisterioPublicoRJ/sinapse#64]
No step 2 alterar o filtro de dropdown para botões.

**Comment by bakudas** [comment]
@victoralves vou exportar também o svg do ícone de check

![image.png](https://images.zenhubusercontent.com/5b3cf068cfaf12775898a112/5856c9e6-f726-409b-ba55-20b269393dcb)

**Comment by bakudas** [comment]
ícone de check para layout

![icon_check.svg](https://images.zenhubusercontent.com/5b3cf068cfaf12775898a112/c709e03b-a8d1-4fed-a65a-a722880ff275)
